spring.application.name=crowdfunding



# ==================================== Configuration de mysql =============================================
server.port=9020
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3308/crowdfunding
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.show-sql=true
spring.jwt.header=Authorization
spring.jwt.secret=48a868a4042f634ac04a117f00a87202131djdhf7477464d7c46c4b32c4acb3edc5e15f4511
# debug=true
spring.http.multipart.max-file-size=15MB
spring.http.multipart.max-request-size=15MB
multipart.enabled=true

# ==================================== Configuration de gmail ==============================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bane8251@gmail.com
spring.mail.password=rkhutojkcizynnwk 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true